# This is a basic workflow to help you get started with Actions

name: Verilog Build and Analysis

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: |
          echo "Install required dependencies"
          sudo apt-get update
          sudo apt-get install iverilog
          sudo apt-get install yosys

      - run: |
          iverilog -o design.o -c script/iverilog.include
          vvp design.o
          yosys -s script/yosys_script.ys > yosys_log.txt
          grep "Latch inferred" yosys_log.txt && { echo "Latches found - fail."; exit 1; } || { echo "No latches found - pass."; exit 0; }
          echo "Script has finished running."
